name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Increment version
        run: |
          python -c "
          import json
          with open('extension/manifest.json', 'r+') as f:
              data = json.load(f)
              version = data['version'].split('.')
              version[-1] = str(int(version[-1]) + 1)
              data['version'] = '.'.join(version)
              f.seek(0)
              json.dump(data, f, indent=2)
              f.truncate()
          "

      - name: Zip the extension
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r extension.zip extension/

      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: "upload"
          extension_id: ${{ secrets.EXTENSION_ID }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          zip_file: extension.zip