name: Publish to Chrome Web Store

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm install -g chrome-webstore-upload-cli bestzip

      - name: Zip the extension
        run: npx bestzip extension.zip extension/

      - name: Package and Upload Extension
        run: |
          /usr/local/bin/webstore upload --source=extension.zip --extension-id=$EXTENSION_ID --client-id=$CLIENT_ID --client-secret=$CLIENT_SECRET --refresh-token=$REFRESH_TOKEN
          /usr/local/bin/webstore publish --extension-id=$EXTENSION_ID --client-id=$CLIENT_ID --client-secret=$CLIENT_SECRET --refresh-token=$REFRESH_TOKEN
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
